# client/Dockerfile.e2e
FROM cypress/included:14.2.0

WORKDIR /app
COPY . .

RUN npm ci
RUN npm install -g wait-on

ENTRYPOINT []

CMD ["sh", "-c", "echo '🧪 Starting Cypress E2E Tests...' && wait-on http://host.docker.internal:5173 && npx cypress run --config baseUrl=http://host.docker.internal:5173"]

