# client/Dockerfile.e2e
FROM cypress/included:14.2.0

WORKDIR /app
COPY . .

RUN npm ci

# 👇 Add curl so we can test connectivity
RUN apt-get update && apt-get install -y curl

RUN npm install -g wait-on

ENTRYPOINT []

CMD ["sh", "-c", "echo '🧪 Starting Cypress E2E Tests...' && wait-on -v http://client:5173 && npx cypress run --config baseUrl=http://client:5173"]



