# =======================
# docker-compose.yml (BASE)
# =======================
services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - db
    networks:
      - app-network

  client:
    build: ./client
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
