version: '3.8'

services:
  client:
    build: ./client
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - '5001:5000' # 🔁 Host:Container
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: tradetap_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
