services:
  db:
    image: postgres:16
    ports:
      - '5433:5432'
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trade_tap
    volumes:
      - trade-tap_pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - '5001:5001'
    env_file:
      - ./server/.env
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - '5173:5173'
    env_file:
      - ./client/.env
    depends_on:
      - server

volumes:
  trade-tap_pgdata:
