# ===================================
# docker-compose.e2e.yml (E2E Testing)
# ===================================
services:
  server:
    command: npm run dev
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env.e2e
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    command: npm run dev
    ports:
      - '5173:5173'
    env_file:
      - ./client/.env.e2e
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./client:/app
      - /app/node_modules

  cypress:
    build:
      context: ./client
      dockerfile: Dockerfile.e2e
    working_dir: /app
    command: npx cypress run --exit
    depends_on:
      - client
    environment:
      - CYPRESS_BASE_URL=${CYPRESS_BASE_URL}
    volumes:
      - ./client:/app
      - /app/node_modules
