# docker-compose.yml
services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - db
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5001/health']
      interval: 5s
      timeout: 2s
      retries: 10

  client:
    build: ./client
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5173']
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
