version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
