# docker-compose.e2e
services:
  client:
    command: npm run dev

  server:
    command: npm run dev

  cypress:
    build:
      context: ./client
      dockerfile: Dockerfile.e2e
    working_dir: /app
    depends_on:
      client:
        condition: service_started
      server:
        condition: service_healthy
    entrypoint: []
    environment:
      - CYPRESS_BASE_URL=http://client:5173
    volumes:
      - ./client:/app
      - /app/node_modules
