# .github/workflows/dummy.yml
name: Enable Environments

on:
  push:
    branches: [main]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "Enabling Environments tab!"
