name: Test Suite

on:
  pull_request:
    branches: [main, develop]

jobs:
  test-client:
    name: Run Client Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install client dependencies
        run: npm install
      - name: Run client unit tests (Vitest)
        run: npm test

  test-server:
    name: Run Server Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install server dependencies
        run: npm install
      - name: Run server unit tests (Vitest)
        run: npm test
